#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "bindings.glsl"

void main() {
  int mid = material_ids[gl_PrimitiveID];
  if (mid < 0 || mid >= params.material_count) {
    mid = 0;
  }
  if (materials[mid].transmission > 0.5) {
    ignoreIntersectionEXT;
  }
  terminateRayEXT;
}
